{% set name = "slovnet" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slovnet-{{ version }}.tar.gz
  sha256: 02d2257bdc9b9cc1d242bd34ee2c861c648f7083ef7898fe1468abcc381ef799

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - navec
    - numpy
    - python
    - razdel

test:
  imports:
    - slovnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/natasha/slovnet
  summary: Deep-learning based NLP modeling for Russian language
  license: MIT
  license_file: LICENSE 

extra:
  recipe-maintainers:
    - harri-pltr 
